config/routes.rb
Lickbo::Application.routes.draw do
  get "stores/index"
  get "stores/show"

  root "product#index"

  resources :products
  resources :stores

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
require 'open-uri'

class ProductsController < ApplicationController

  def index
    @products = JSON.parse(open('http://lcboapi.com/products?per_page=60').read)
  end

  def show
    product_json = open("http://lcboapi.com/products/#{params[:id]}").read
    index_json = JSON.parse(product_json)
    @product = index_json['result']
  end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
    @stores = JSON.parse(open('http://lcboapi.com/stores?per_page=60').read)
  end

  def show
    store_json = open("http://lcboapi.com/stores/#{params[:id]}").read
    index_json = JSON.parse(store_json)
    @store = index_json['result']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_numbers(numbers)
    processed = numbers.to_f/100.00
    sprintf("%.2f", processed)
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lickbo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<h1>Please Drink Responsibldaskfljasdf, NAH.</h1>

<% @products['result'].each do |product| %>
  <div class="product">
    <%= link_to product['name'], product_path(product['id']) %> - 
    $<%= format_numbers product['price_in_cents'] %></br>
      <% if product['image_thumb_url'] == nil %> 
        <%= image_tag ("http://www.definitivetech.com/images/products/product_image_not_available.gif") %> 
      <% else %>
        <%= link_to image_tag(product['image_thumb_url']), product_path(product['id']) %>
      <% end %>
  </div>
<% end %>

app/views/products/show.html.erb
<h1>Product Details</h1>

<%= link_to 'Back', products_path %>

<p><%= @product['name'] %> - <%= format_numbers @product['alcohol_content'] %>%</p>

<%= @product['primary_category'] %>
<%= @product['secondary_category'] %>
<%= @product['origin'] %>

<p>
$<%= format_numbers(@product['price_in_cents']) %> for 
<%= @product['package'] %></p>


<%= image_tag @product['image_url'] %>

app/views/stores/index.html.erb
<h1>Stores Index</h1>

<ol>
  <% @stores['result'].each do |store| %>
    <div class="store">
      <li><%= link_to store['name'], store_path(store['id']) %></li>
      <%= store['address_line_1'] %>
    </div>
  <% end %>
</ol>

app/views/stores/show.html.erb
<h1>Store Details</h1>

<%= link_to 'Back', stores_path %>

<p><%= @store['name'] %> - ID <%= @store['id'] %></p>

<%= @store['address_line_1'] %></br>
<%= @store['address_line_2'] %></br>
<%= @store['city'] %></br>
<%= @store['postal_code'] %></br>
Telephone: <%= @store['telephone'] %></br>